version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-mdx
    versions:
    - 2.0.0
  - dependency-name: inquirer
    versions:
    - 8.0.0
